# Cloud Build configuration for Cloud Run deployment
# Usage: gcloud builds submit --config=cloudbuild.yaml

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/tru-s3-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/tru-s3-backend:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tru-s3-backend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tru-s3-backend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'backend',
      '--image', 'gcr.io/$PROJECT_ID/tru-s3-backend:$BUILD_ID',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--cpu', '1',
      '--memory', '512Mi',
      '--timeout', '300',
      '--concurrency', '80',
      '--max-instances', '10',
      '--set-env-vars', 'GIN_MODE=release,USE_CLOUD_SQL_PROXY=true,CLOUD_SQL_CONNECTION_NAME=zenn-ai-agent-hackathon-460205:asia-northeast1:prd-db,DB_NAME=tru_s3,DB_USER=postgres,DB_SSL_MODE=require,GCS_BUCKET_NAME=202506-zenn-ai-agent-hackathon,GCS_FOLDER=test,GOOGLE_CLOUD_PROJECT=$PROJECT_ID',
      '--set-secrets', 'DB_PASSWORD=db-password:latest',
      '--add-cloudsql-instances', 'zenn-ai-agent-hackathon-460205:asia-northeast1:prd-db'
    ]

# Build-time substitutions
substitutions: {}

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'
