version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tru_s3
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_SSL_MODE=disable
    volumes: []
    restart: unless-stopped
    depends_on:
      - db
    
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: tru_s3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
